spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/student
    username: 
    password: 
server:
  servlet:
    context-path: /ex-intermediate
